#!/usr/bin/env node

// Forge Game - Web Standards Entry for Liberated Pixel Cup
// Copyright (C) 2012  Azlen Elza
//  
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//  
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//  
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.


console.log('process.argv: %j', process.argv);

var maxX = parseInt(process.argv[2]);
var maxY = parseInt(process.argv[3]);

var alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'

var css = [];
var js = [];

for (var x = 0; x < maxX ; x++){
    for (var y = 0; y < maxY; y++){
        var dx = x ? -32 * x : 0;
        var dy = y ? -32 * y : 0;
        css.push('.' + alpha[x] + alpha[y] + '{ background-position: ' + dx + 'px ' + dy + 'px; }');
        dx = Math.abs(dx);
        dy = Math.abs(dy);
        js.push(alpha[x] + alpha[y] + ': { x: ' + dx + ', y: ' + dy + ' },');
    }
}

console.log('CSS for editor/index.html:');
css.forEach(function(line){
    console.log('\t\t' + line);
});
console.log('\nJS for public/js/world.js:');
js.forEach(function(line){
    console.log('\t' + line);
});
console.log('');
        